project:
  name: bb-unified-election-data
  description: ''
  tools: []
  current_focus: ''
  needs: []
  links:
    docs: ''
    staging: ''
    production: ''
  team:
    lead: pauldingus
    contributors: []
  campaign:
    candidate: ''
    office: ''
  auto_refresh: true
